# Generated by Django 3.0.2 on 2020-01-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
                ('thoughts', models.CharField(max_length=5000)),
                ('read_date', models.DateTimeField(verbose_name='date read')),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
