# Generated by Django 3.0.2 on 2020-01-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200126_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='synopsis',
        ),
    ]
