# Generated by Django 3.0.2 on 2020-01-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200126_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thoughts',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
