# Generated by Django 3.0.2 on 2020-01-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200127_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.CharField(choices=[('☆☆☆☆☆', 'None'), ('★☆☆☆☆', 'One star'), ('★★☆☆☆', 'Two stars'), ('★★★☆☆', 'Three stars'), ('★★★★☆', 'Four stars'), ('★★★★★', 'Five stars')], default='☆☆☆☆☆', max_length=255),
        ),
    ]
