# Generated by Django 3.0.2 on 2020-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200127_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='thoughts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
