# Generated by Django 3.0.2 on 2020-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200128_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
